# Generated by Django 5.0.4 on 2024-04-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida_arancelaria', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=200)),
                ('referencia', models.CharField(editable=False, max_length=10)),
                ('peso_neto', models.FloatField()),
                ('peso_bruto', models.FloatField()),
            ],
        ),
    ]
