# Generated by Django 5.0.4 on 2024-04-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0002_alter_producto_descripcion_alter_producto_referencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['referencia'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='referencia',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
