# Generated by Django 5.0.4 on 2024-04-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0007_cliente_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=30)),
                ('logo_empresa', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Imagen')),
                ('direccion_empresa', models.CharField(max_length=50)),
                ('forma_pago', models.TextField(max_length=150)),
                ('cod_camara', models.CharField(max_length=10)),
                ('nombre_encargado', models.CharField(max_length=30)),
                ('cod_encargado', models.CharField(max_length=10)),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre_empresa'],
            },
        ),
    ]
