# Generated by Django 5.0.4 on 2024-04-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0009_rename_cod_encargado_empresa_cargo_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion_cliente',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cargo_encargado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion_empresa',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre_pais',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion_proveedor',
            field=models.CharField(max_length=300),
        ),
    ]
