# Generated by Django 5.0.4 on 2024-04-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0010_alter_cliente_direccion_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_importadora', models.CharField(max_length=100)),
                ('direccion_importadora', models.CharField(max_length=500)),
                ('contrato', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Importadora',
                'verbose_name_plural': 'Importadoras',
                'ordering': ['nombre_importadora'],
            },
        ),
    ]
