# Generated by Django 5.0.4 on 2024-04-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0011_importadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo_empresa',
            field=models.ImageField(null=True, upload_to='logo_empresa/'),
        ),
    ]
