# Generated by Django 5.0.4 on 2024-04-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0012_alter_empresa_logo_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo_empresa',
            field=models.ImageField(blank=True, null=True, upload_to='logo_empresa/'),
        ),
    ]
