# Generated by Django 5.0.4 on 2024-04-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0013_alter_empresa_logo_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cod_camara',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_encargado',
            field=models.CharField(max_length=100),
        ),
    ]
