# Generated by Django 5.0.4 on 2024-04-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0016_unidaddemedida_producto_unidad_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaArancelaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.CharField(max_length=50)),
            ],
        ),
    ]
