# Generated by Django 5.0.4 on 2024-04-30 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0017_partidaarancelaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='partida_arancelaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_online.partidaarancelaria'),
        ),
    ]
