# Generated by Django 5.0.4 on 2024-05-01 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0019_partidaarancelaria_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cubicaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seguro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('otros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('identificador', models.CharField(max_length=500)),
                ('sello', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_online.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_online.empresa')),
                ('importadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_online.importadora')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_online.proveedor')),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_online.puerto')),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
                'ordering': ['identificador'],
            },
        ),
    ]
