# Generated by Django 5.0.4 on 2024-05-01 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0020_contenedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_online.cliente', to_field='nombre_cliente'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_online.empresa', to_field='nombre_empresa'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='importadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_online.importadora', to_field='nombre_importadora'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_online.proveedor', to_field='nombre_proveedor'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='puerto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_online.puerto', to_field='nombre_puerto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_empresa',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='importadora',
            name='nombre_importadora',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
