# Generated by Django 5.0.4 on 2024-05-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0022_alter_contenedor_cliente_alter_contenedor_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLenarContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bruto_kg', models.FloatField()),
                ('neto_kg', models.FloatField()),
                ('bultos', models.PositiveIntegerField()),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_online.contenedor')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_online.producto')),
            ],
            options={
                'verbose_name': 'LLenarContenedor',
                'verbose_name_plural': 'LLenarContenedores',
                'ordering': ['contenedor'],
            },
        ),
    ]
