# Generated by Django 5.0.4 on 2024-05-03 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0023_llenarcontenedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llenarcontenedor',
            name='contenedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tienda_online.contenedor'),
        ),
    ]
