# Generated by Django 5.0.4 on 2024-05-09 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0025_alter_contenedor_options_contenedor_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenedor',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Contenedor', 'verbose_name_plural': 'Contenedores'},
        ),
        migrations.AddField(
            model_name='puerto',
            name='pais_puerto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_online.pais'),
        ),
    ]
