# Generated by Django 5.0.4 on 2024-05-10 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0026_alter_contenedor_options_puerto_pais_puerto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenedor',
            name='puerto',
        ),
        migrations.AddField(
            model_name='contenedor',
            name='puerto_destino',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenedores_destino', to='tienda_online.puerto'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='puerto_origen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenedores_origen', to='tienda_online.puerto'),
        ),
    ]
