# Generated by Django 5.0.4 on 2024-05-14 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0028_alter_contenedor_puerto_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_transporte', models.CharField(max_length=10)),
                ('descripcion_transporte', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'ordering': ['nombre_transporte'],
            },
        ),
        migrations.RemoveField(
            model_name='contenedor',
            name='otros',
        ),
        migrations.AddField(
            model_name='contenedor',
            name='transporte',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_online.transporte'),
        ),
    ]
