# Generated by Django 5.0.4 on 2024-05-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0030_contenedor_hbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='factura',
            field=models.CharField(blank=True, default=None, editable=False, max_length=15, null=True, unique=True),
        ),
    ]
