# Generated by Django 5.0.4 on 2024-05-14 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0031_contenedor_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=0)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='contenedor',
            name='estado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_online.estado'),
        ),
    ]
