# Generated by Django 5.0.4 on 2024-05-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0032_estado_contenedor_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['orden'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pin',
            field=models.CharField(default=1234, max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
