# Generated by Django 5.0.7 on 2024-07-19 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0035_alter_empresa_firma_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedidaContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'UnidadMedidaContenedor',
                'verbose_name_plural': 'UnidadMedidaContenedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='empresa',
            name='firma_empresa',
            field=models.ImageField(blank=True, default='defaults/default.png', null=True, upload_to='firma_empresa/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo_empresa',
            field=models.ImageField(blank=True, default='defaults/default.png', null=True, upload_to='logo_empresa/'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='unidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda_online.unidadmedidacontenedor'),
        ),
    ]
