# Generated by Django 5.0.7 on 2024-07-19 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0036_unidadmedidacontenedor_alter_empresa_firma_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='unidad',
            field=models.ForeignKey(blank=True, default='LB', null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_online.unidadmedidacontenedor'),
        ),
    ]
