# Generated by Django 5.0.7 on 2024-07-19 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0039_alter_contenedor_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda_online.unidadmedidacontenedor'),
        ),
    ]
