# Generated by Django 5.0.7 on 2024-07-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0040_alter_contenedor_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenedor',
            name='unidad',
        ),
    ]
