# Generated by Django 5.0.7 on 2024-07-19 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0042_alter_unidadmedidacontenedor_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda_online.unidadmedidacontenedor'),
        ),
        migrations.AlterField(
            model_name='unidadmedidacontenedor',
            name='nombre',
            field=models.CharField(default='Libras', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidadmedidacontenedor',
            name='sigla',
            field=models.CharField(default='LB', max_length=5),
            preserve_default=False,
        ),
    ]
