# Generated by Django 5.0.7 on 2024-07-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0044_alter_unidadmedidacontenedor_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
