# Generated by Django 5.0.7 on 2024-07-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0046_alter_contenedor_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedidacontenedor',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unidadmedidacontenedor',
            name='sigla',
            field=models.CharField(max_length=5),
        ),
    ]
