# Generated by Django 5.0.4 on 2024-06-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('cambio_cup', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cambio',
                'verbose_name_plural': 'Cambios',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=11, unique=True)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('direccion_cliente', models.CharField(max_length=300)),
                ('telefono_cliente', models.CharField(max_length=8)),
                ('correo_cliente', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Cliente',
                'ordering': ['ci'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('direccion_empresa', models.CharField(max_length=300)),
                ('telefono_empresa', models.CharField(max_length=8)),
                ('correo_empresa', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nit'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=20)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('imagen_producto', models.ImageField(upload_to='imagen_producto/,blank=True,null=True')),
                ('cantidad_inicio', models.IntegerField()),
                ('precio_usd', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('impuesto_cup', models.IntegerField(default=0)),
                ('empaquetado', models.IntegerField()),
                ('cantidad_congelada', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id_producto'],
            },
        ),
    ]
